url: https://rickykuang.com

collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      permalink: "/projects/:title:output_ext"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/blog/:year/:month/:day/:title:output_ext"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  # - jekyll-target-blank
